// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG0VUCgcR2FvCithapOt3mZXLuDKHNNNI',
    appId: '1:497804653990:web:417468e09a4cd089f84b67',
    messagingSenderId: '497804653990',
    projectId: 'do-an-a-5f5f7',
    authDomain: 'do-an-a-5f5f7.firebaseapp.com',
    storageBucket: 'do-an-a-5f5f7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqJ4I53uktdFYLpnoqLWmO72U0T1G0LKI',
    appId: '1:497804653990:android:ac70d2c40227e0acf84b67',
    messagingSenderId: '497804653990',
    projectId: 'do-an-a-5f5f7',
    storageBucket: 'do-an-a-5f5f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdg_QfpQTBccINtmWGxLMdK1xIbd5FEiw',
    appId: '1:497804653990:ios:63d0cfc371a34ee4f84b67',
    messagingSenderId: '497804653990',
    projectId: 'do-an-a-5f5f7',
    storageBucket: 'do-an-a-5f5f7.appspot.com',
    iosClientId: '497804653990-o1gnc8slg6nr51167pqbs3ckhbekho5o.apps.googleusercontent.com',
    iosBundleId: 'com.example.doAn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdg_QfpQTBccINtmWGxLMdK1xIbd5FEiw',
    appId: '1:497804653990:ios:63d0cfc371a34ee4f84b67',
    messagingSenderId: '497804653990',
    projectId: 'do-an-a-5f5f7',
    storageBucket: 'do-an-a-5f5f7.appspot.com',
    iosClientId: '497804653990-o1gnc8slg6nr51167pqbs3ckhbekho5o.apps.googleusercontent.com',
    iosBundleId: 'com.example.doAn',
  );
}
